### PR TITLE
Added an .desktop file

### PR DESCRIPTION
**Pull request by Wabuo**
-added a .desktop file
-renamed the logo to fit the .desktop file standard

### CODE REVIEW

**Comment by oakes** [comment]
Thanks, I'll look at this soon. Did you mean to put .desktop the file name twice?

**Comment by Wabuo** [comment]
Oo sorry no xD

**Comment by oakes** [comment]
Thanks. Also, would it be better to commit the png version, or does this format support svg?

**Comment by Wabuo** [comment]
All modern desktop environments support svg. The standard says:  An icon file is an image that can be loaded and used as an icon. The supported image file formats are PNG, XPM and SVG. PNG is the recommended bitmap format, and SVG is for vectorized icons. XPM is supported due to backwards compability reasons, and it is not recommended that new themes use XPM files. Support for SVGs is optional.

**Comment by Wabuo** [comment]
I would prefer the svg over the png because it is smaller and you don't have to mess around with the resolutions ...

**Comment by oakes** [comment]
Thanks!

**Pull request merged**
